version: '3.9'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"