version: '3.9'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - "3306:3306"

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./target/backend-1.0-exec.jar:/app.jar
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/database?allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "${DB_ROOT_PASSWORD}",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "driver-class-name" : "com.mysql.cj.jdbc.Driver"
            }'
