##CONNECTION TO DB
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

##SERVER CONFIGURATION
server:
  port: ${SERVER_PORT}

##SECRET KEY FOR JWT
jwt-key: ${SECRET_KEY}

