##CONNECTION TO DB
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false

##SERVER CONFIGURATION
server:
  port: ${SERVER_PORT}

##SECRET KEY FOR JWT
jwt-key: ${SECRET_KEY}

